spring:
  config:
    import: "optional:configserver:"
  application:
    name: "gateway"

  cloud:
    gateway:
      routes:
        - id: greetings
          uri: "http://localhost:64412/greetings"
          predicates:
            - Path=/greetings/**


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8761/eureka"